# Generated by Django 2.0.13 on 2019-03-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('author_name', models.CharField(max_length=40, null=True)),
                ('biography', models.TextField()),
                ('birthday_date', models.DateTimeField(blank=True, null=True)),
                ('death_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('category_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.Authors')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.BookCategory')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
